// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	Name          string
	Url           string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
}

type Follow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedID    uuid.UUID
	UserID    uuid.UUID
}

type Post struct {
	ID          uuid.UUID
	Title       string
	Description string
	Url         string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FeedID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
